### ISSUE TITLE
Deprecate/ add disclaimer to prefer !tagged built into symfony DI

### ISSUE THREAD

**Issue by ostrolucky** [mlebkowski/registry-compiler#4]
Since Symfony 3.4, standalone DependencyInjection container has built in [functionality for collecting services with certain tag](https://symfony.com/doc/3.4/service_container/tags.html#reference-tagged-services), which is what this library is all about.

There is not much this library offers on top of that. I think you should deprecate it, enhance it or add disclaimer to prefer !tagged if use case doesn't require more features.

**Comment by mlebkowski** [comment]
This lib targets Symfony 2, and there is no such functionality in that framework.
